server:
  port: 8080
  cloud:
    gateway:
      routes:

        # User Service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**

        # Product Service
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**

        # Order Service
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order/**

        # Inventory Service
        - id: inventory-service
          uri: http://localhost:8084
          predicates:
            - Path=/inventory/**

        # Cart Service
        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/cart/**

        # Payment Service
        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/payment/**

        # Rating / Review Service
        - id: rating-service
          uri: http://localhost:8087
          predicates:
            - Path=/rating/**

